### ISSUE TITLE
use crypto module

### ISSUE THREAD

**Issue by defunctzombie** [yanxi123-com/npm-random-key#1]
Math.random() is not actually random.

**Comment by yanxi123-com** [comment]
thanks, I have changed code using crypto.randomBytes.
https://github.com/yanxi-com/nodejs-random-key/commit/85bcf165f3870c8996a1a28376be5909d14123dd

**Comment by moloch--** [comment]
Unfortunately the code to fix this issue contains a more subtle bug that results in cryptographically insecure key generation. The [use of modulus on line #4](https://github.com/yanxi-com/nodejs-random-key/blob/master/index.js#L4) produces a non-uniform distribution across 0 -> `max`. This bias results in keys that are not suitable for cryptographic use.

### Additional Resources

[Examining the Modulus of Random Variables](https://erikerlandson.github.io/blog/2013/03/15/examining-the-modulus-of-random-variables/) 
[Modulo Bias When Using Random Number Generators](https://stackoverflow.com/questions/10984974/why-do-people-say-there-is-modulo-bias-when-using-a-random-number-generator)
[How PRNGs Work and How to Break Them](https://www.youtube.com/watch?v=f841Y7d3oDo)

### Remediation

The simplest solution (though rather inefficient) is to simply continue reading `randomBytes` until a value is produced that lands between 0 and `max`. More complicated solutions are presented the the links above.

**Comment by markstos** [comment]
Thanks for the review @moloch-- Is there another module you recommend insteand for generating strings like this in Node.js?
